-- Add primary key and unique key to AIR_AIRPORTS
ALTER TABLE AIR_AIRPORTS
ADD CONSTRAINT PK_AIR_AIRPORTS PRIMARY KEY("AIRPORT_ID");

ALTER TABLE AIR_AIRPORTS
ADD CONSTRAINT AK1_AIR_AIRPORTS UNIQUE("ICAO");

-- Add primary key and foreign key to AIR_AIRPORTS_GEO
ALTER TABLE AIR_AIRPORTS_GEO
ADD CONSTRAINT PK_AIR_AIRPORTS_GEO PRIMARY KEY("AIRPORT_ID");

ALTER TABLE AIR_AIRPORTS_GEO
ADD CONSTRAINT FK_AIR_AIRPORTS_GEO_AIRPORT FOREIGN KEY("AIRPORT_ID")
    REFERENCES AIR_AIRPORTS("AIRPORT_ID");

-- Add primary key and foreign key to AIR_AIRLINES
ALTER TABLE AIR_AIRLINES
ADD CONSTRAINT PK_AIR_AIRLINES PRIMARY KEY("AIRLINE_ID");

ALTER TABLE AIR_AIRLINES
ADD CONSTRAINT AK1_AIR_AIRLINES UNIQUE("IATA");

ALTER TABLE AIR_AIRLINES
ADD CONSTRAINT FK_AIR_AIRLINES_AIRPORT FOREIGN KEY("BASE_AIRPORT_ID")
    REFERENCES AIR_AIRPORTS("AIRPORT_ID");

-- Add primary key to AIR_AIRPLANE_TYPES
ALTER TABLE AIR_AIRPLANE_TYPES
ADD CONSTRAINT PK_AIR_AIRPLANE_TYPES PRIMARY KEY("AIRPLANE_TYPE_ID");

-- Add primary key and foreign keys to AIR_AIRPLANES
ALTER TABLE AIR_AIRPLANES
ADD CONSTRAINT PK_AIR_AIRPLANES PRIMARY KEY("AIRPLANE_ID");

ALTER TABLE AIR_AIRPLANES
ADD CONSTRAINT FK_AIR_AIRPLANES_AIRLINE FOREIGN KEY("AIRLINE_ID")
    REFERENCES AIR_AIRLINES("AIRLINE_ID");

ALTER TABLE AIR_AIRPLANES
ADD CONSTRAINT FK_AIR_AIRPLANES_AIRPLANE_TYPE FOREIGN KEY("AIRPLANE_TYPE_ID")
    REFERENCES AIR_AIRPLANE_TYPES("AIRPLANE_TYPE_ID");

-- Add primary key and foreign keys to AIR_FLIGHTS_SCHEDULES
ALTER TABLE AIR_FLIGHTS_SCHEDULES
ADD CONSTRAINT PK_AIR_FLIGHTS_SCHEDULES PRIMARY KEY("FLIGHTNO");

ALTER TABLE AIR_FLIGHTS_SCHEDULES
ADD CONSTRAINT FK_AIR_F_S_AIRLINE FOREIGN KEY("AIRLINE_ID")
    REFERENCES AIR_AIRLINES("AIRLINE_ID");

ALTER TABLE AIR_FLIGHTS_SCHEDULES
ADD CONSTRAINT FK_AIR_F_S_DEPARTURE_AIRPORT FOREIGN KEY("FROM_AIRPORT_ID")
    REFERENCES AIR_AIRPORTS("AIRPORT_ID");

ALTER TABLE AIR_FLIGHTS_SCHEDULES
ADD CONSTRAINT FK_AIR_F_S_ARRIVAL_AIRPORT FOREIGN KEY("TO_AIRPORT_ID")
    REFERENCES AIR_AIRPORTS("AIRPORT_ID");

-- Add primary key and foreign keys to AIR_FLIGHTS
ALTER TABLE AIR_FLIGHTS
ADD CONSTRAINT PK_AIR_FLIGHTS PRIMARY KEY("FLIGHT_ID");

ALTER TABLE AIR_FLIGHTS
ADD CONSTRAINT FK_AIR_F_FLIGHTNO FOREIGN KEY("FLIGHTNO")
    REFERENCES AIR_FLIGHTS_SCHEDULES("FLIGHTNO");

ALTER TABLE AIR_FLIGHTS
ADD CONSTRAINT FK_AIR_F_AIRLINE FOREIGN KEY("AIRLINE_ID")
    REFERENCES AIR_AIRLINES("AIRLINE_ID");

ALTER TABLE AIR_FLIGHTS
ADD CONSTRAINT FK_AIR_F_DEPARTURE_AIRPORT FOREIGN KEY("FROM_AIRPORT_ID")
    REFERENCES AIR_AIRPORTS("AIRPORT_ID");

ALTER TABLE AIR_FLIGHTS
ADD CONSTRAINT FK_AIR_F_ARRIVAL_AIRPORT FOREIGN KEY("TO_AIRPORT_ID")
    REFERENCES AIR_AIRPORTS("AIRPORT_ID");

ALTER TABLE AIR_FLIGHTS
ADD CONSTRAINT FK_AIR_F_AIRPLANE FOREIGN KEY("AIRPLANE_ID")
    REFERENCES AIR_AIRPLANES("AIRPLANE_ID");

-- Add primary key to AIR_PASSENGERS_DETAILS
ALTER TABLE AIR_PASSENGERS_DETAILS
ADD CONSTRAINT PK_AIR_PASSENGERS_DETAILS PRIMARY KEY("PASSENGER_ID");

-- Add primary key and unique key to AIR_PASSENGERS
ALTER TABLE AIR_PASSENGERS
ADD CONSTRAINT PK_AIR_PASSENGERS PRIMARY KEY("PASSENGER_ID");

ALTER TABLE AIR_PASSENGERS
ADD CONSTRAINT AK1_AIR_PASSENGERS UNIQUE("PASSPORTNO");

-- Add primary key, foreign keys, and unique keys to AIR_BOOKINGS
ALTER TABLE AIR_BOOKINGS
ADD CONSTRAINT PK_AIR_BOOKINGS PRIMARY KEY("BOOKING_ID");

ALTER TABLE AIR_BOOKINGS
ADD CONSTRAINT FK_AIR_BOOKINGS_PASSENGER FOREIGN KEY("PASSENGER_ID")
    REFERENCES AIR_PASSENGERS("PASSENGER_ID");

ALTER TABLE AIR_BOOKINGS
ADD CONSTRAINT FK_AIR_BOOKINGS_FLIGHT FOREIGN KEY("FLIGHT_ID")
    REFERENCES AIR_FLIGHTS("FLIGHT_ID");

ALTER TABLE AIR_BOOKINGS
ADD CONSTRAINT AK2_AIR_BOOKINGS UNIQUE("FLIGHT_ID", "SEAT");
